CREATE TABLE wallet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id VARCHAR(255) UNIQUE NOT NULL
);


CREATE TABLE wallet_balance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance_type VARCHAR(255) NOT NULL,
    balance DECIMAL(18, 2) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE merchant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE,
    mcc BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

ALTER TABLE wallet_balance
ADD COLUMN wallet_id BIGINT;

ALTER TABLE wallet_balance
ADD CONSTRAINT fk_wallet
FOREIGN KEY (wallet_id) REFERENCES wallet(id);

CREATE INDEX idx_wallet_account_id ON wallet(account_id);